### ISSUE TITLE
backend只单个部署，单点问题怎么解决呢？

### ISSUE THREAD

**Issue by kaojunsong** [chanjarster/artemis-disruptor-miaosha#1]
库存数据都在内存里，如果这个单点挂了怎么办呢

**Comment by chanjarster** [comment]
如果你能够接受backend挂，那么只需重启backend就又能恢复工作了，参考[崩溃恢复方案][1]。

如果不能接受单点down，那么可以参考[The LMAX Architecture][2]，做一个Replicator，保证第一个节点挂了，第二个节点马上顶上去：

> The replication allows them to do this with no downtime, so they continue to process trades 24/7

上面这两个方案在本项目里均未实现。

[1]: https://github.com/chanjarster/artemis-disruptor-miaosha/blob/master/Recover_Solution.md
[2]: https://martinfowler.com/articles/lmax.html

**Comment by kaojunsong** [comment]
明白你的意思啦，赞一个

**Comment by JsonSong89** [comment]
那意思是这个系统不支持弹性扩容?

**Comment by chanjarster** [comment]
@JsonSong89 不支持
