### ISSUE TITLE
Could not start artemis-service

### ISSUE THREAD

**Issue by chenwin** [chanjarster/artemis-disruptor-miaosha#3]
照着文档一步步装下来，执行 miaosha-broker/bin/artemis-service start报错，“Could not start artemis-service”，没有日志，也不知道错在哪里 ？百度和Google上也没有相关信息，如何解决？

**Comment by fengxiutianya** [comment]
可以先使用artemis run这个命令运行，可以打印出运行时的一些日志，然后从日志中可以看到哪里出问题

**Comment by chenwin** [comment]
多谢，已解决。
