### ISSUE TITLE
单点问题如何解决

### ISSUE THREAD

**Issue by wangkezun** [chanjarster/artemis-disruptor-miaosha#5]
看readme中说明backend只能单点部署，这种情况单点宕机后如何恢复呢？

**Comment by chanjarster** [comment]
[恢复方案](https://github.com/chanjarster/artemis-disruptor-miaosha/blob/master/Recover_Solution.md)

不过这个只是一个思路，没有代码实现。

**Comment by wangkezun** [comment]
噢。抱歉。没拉到readme最下面看。。了解思路了。多谢
